apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zkpassport-cloud-prover

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - backendconfig.yaml
  - managedcertificate.yaml
  - ingress.yaml
  - hpa.yaml

# CI runs `kustomize edit set image` to pin the freshly built tag.
images:
  - name: us-central1-docker.pkg.dev/zkpassport-cloud-prover/cloud-prover/cloud-prover
    newTag: latest
